### ISSUE TITLE
This is crazy

### ISSUE THREAD

**Issue by clxyify** [kevlu8/Xytharis#6]
Wow this is crazy and distructive.
Here are a few suggestions:

Make screen black and white.
Freeze screen for a random amount of time.
Download random txt files.
FIll the desktop with Xyatharis.

**Comment by kevlu8** [comment]
Thanks for your suggestions! Unfortunately, I have stopped working on this project. However, I will try to implement this into my future projects!

**Comment by winapiadmin** [comment]
"Download random txt files."
How did and why downloading it? it take longer than any payload. creating manually is faster.

**Comment by kevlu8** [comment]
As I said, this project was made to help me learn C++. The code in this project is nowhere near good, and half the payloads don't work properly. I have learned C++ now, and thus have stopped working on this project. It's just kept open for people to download and try this malware if they want.
